/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import static com.mysql.cj.conf.PropertyKey.logger;
import controller.ProductoDAO;
import model.*;
import javax.swing.JOptionPane;
import java.util.logging.Logger;
import java.util.logging.Level;
/**
 *
 * @author maxan
 */
public class DistribuidoraVIew extends javax.swing.JFrame {
    
    private Producto producto;  // ← Cambio: Instancia del modelo, no del DAO
    
    /**
     * Creates new form DistribuidoraVIew
     */
    public DistribuidoraVIew() {
        initComponents();
        limpiarCampos();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSKU = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblEdicion = new javax.swing.JLabel();
        lblLinea = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblFechaSalida = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblCantidadMazo = new javax.swing.JLabel();
        lblCantidadSobre = new javax.swing.JLabel();
        lblRegaloExtra = new javax.swing.JLabel();
        lblCartaPromo = new javax.swing.JLabel();
        lblCantidadSobreEspecial = new javax.swing.JLabel();
        txtSKU = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtEdicion = new javax.swing.JTextField();
        txtLinea = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtFechaSalida = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtCantidadSobre = new javax.swing.JTextField();
        txtCantidadMazos = new javax.swing.JTextField();
        txtCantidadSobresEspeciales = new javax.swing.JTextField();
        txtCartaPromocional = new javax.swing.JTextField();
        txtRegaloEspecial = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        cmbTipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSKU.setText("SKU");

        lblNombre.setText("Nombre");

        lblEdicion.setText("Edición");

        lblLinea.setText("Linea");

        lblTipo.setText("Tipo");

        lblStock.setText("Stock");

        lblPrecio.setText("Precio");

        lblFechaSalida.setText("Fecha Salida");

        lblDescripcion.setText("Descripción");

        lblCantidadMazo.setText("Cantidad Sobre");

        lblCantidadSobre.setText("Cantidad Mazos");

        lblRegaloExtra.setText("Regalo Extra");

        lblCartaPromo.setText("Carta Promocional");

        lblCantidadSobreEspecial.setText("Cantidad Sobres Especial");

        txtSKU.addActionListener(this::txtSKUActionPerformed);

        txtPrecio.addActionListener(this::txtPrecioActionPerformed);

        txtDescripcion.addActionListener(this::txtDescripcionActionPerformed);

        txtCartaPromocional.addActionListener(this::txtCartaPromocionalActionPerformed);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        cmbTipo.setEditable(true);
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Opción", "Caja Mazos", "Caja Sobres", "Caja Especial", " " }));
        cmbTipo.addActionListener(this::cmbTipoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(lblEdicion))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblStock, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPrecio)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(lblSKU, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtFechaSalida)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEdicion)
                            .addComponent(txtLinea, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecio)
                            .addComponent(txtStock, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSKU, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblDescripcion)
                        .addGap(78, 78, 78)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRegaloExtra)
                                .addGap(108, 108, 108))
                            .addComponent(lblCartaPromo, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblCantidadSobre)
                            .addGap(54, 54, 54)
                            .addComponent(txtCantidadMazos, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblCantidadSobreEspecial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCantidadSobresEspeciales)
                            .addComponent(txtRegaloEspecial)
                            .addComponent(txtCartaPromocional, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblCantidadMazo)
                        .addGap(58, 58, 58)
                        .addComponent(txtCantidadSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(btnGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSKU)
                    .addComponent(txtSKU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantidadSobre)
                    .addComponent(txtCantidadMazos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEdicion)
                            .addComponent(txtEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLinea)
                            .addComponent(txtLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStock)
                            .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCantidadMazo)
                            .addComponent(txtCantidadSobre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCantidadSobreEspecial)
                            .addComponent(txtCantidadSobresEspeciales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCartaPromo)
                            .addComponent(txtCartaPromocional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRegaloEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRegaloExtra))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaSalida)
                    .addComponent(txtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(btnGuardar)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
            try {
     
            String sku = txtSKU.getText().trim();
            String nombre = txtNombre.getText().trim();
            String edicion = txtEdicion.getText().trim();
            String linea = txtLinea.getText().trim();
            String tipo = cmbTipo.getSelectedItem().toString();
            if (tipo.equals("Caja Mazos")){
            tipo = "Caja Mazos";}
            else if (tipo.equals("Caja Sobres")){
                tipo = "Caja Sobres";
            }
            else if (tipo.equals("Caja Especial")){
                tipo = "Caja Especial";
            }
            int stock = Integer.parseInt(txtStock.getText().trim());
            int precio = Integer.parseInt(txtPrecio.getText().trim());
            String fechaSalida = txtFechaSalida.getText().trim();
            String descripcion = txtDescripcion.getText().trim();
            int cantidadSobre = Integer.parseInt(txtCantidadSobre.getText().trim());
            int cantidadMazo = Integer.parseInt(txtCantidadMazos.getText().trim());
            int cantidadSobreEspecial = Integer.parseInt(txtCantidadSobresEspeciales.getText().trim());
            String cartaPromo = txtCartaPromocional.getText().trim();
            String regaloExtra = txtRegaloEspecial.getText().trim();

   
            if (sku.isEmpty() || nombre.isEmpty() || edicion.isEmpty() || tipo.isEmpty()) {
                 JOptionPane.showMessageDialog(this, "Faltan datos obligatorios.");
                 return;
            }


            
            producto = null; 

      
            switch (tipo) {
                case "Caja Sobres":
                    producto = new CajaSobre(cantidadSobre, edicion, nombre, linea, tipo, stock, precio, sku, fechaSalida, descripcion);
                    break;
                case "Caja Mazos":
                    producto = new CajaMazo(cantidadMazo, edicion, nombre, linea, tipo, stock, precio, sku, fechaSalida, descripcion);
                    break;
                case "Caja Especial":
                
                    producto = new CajaEspecial(cantidadSobreEspecial, cartaPromo, regaloExtra, edicion, nombre, linea, tipo, stock, precio, sku, fechaSalida, descripcion);
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "El TIPO debe ser: CajaSobre, CajaMazo o CajaEspecial");
                    return;
            }

            if (producto != null) {

                ProductoDAO dao = new ProductoDAO();

                if (dao.insertar(producto)) {
                    JOptionPane.showMessageDialog(this, "¡Producto guardado con éxito!");
                    limpiarCampos();
                } else {
                    JOptionPane.showMessageDialog(this, "Hubo un error al guardar en la Base de Datos. Revisa la consola.");
                }
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: Revisa que Stock, Precio y Cantidades sean números.");
        } catch (Exception e) {
            System.out.println("Error grave: " + e.getMessage());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtSKUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSKUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSKUActionPerformed

    private void txtCartaPromocionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCartaPromocionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCartaPromocionalActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
          if ("Caja Mazos".equals(cmbTipo.getSelectedItem())){
              accionCajaMazo();
          }
          
          if ("Caja Sobres".equals(cmbTipo.getSelectedItem())){
              accionCajaSobre();
          }
          
          if ("Caja Especial".equals(cmbTipo.getSelectedItem())){
              accionCajaEspecial();
          }
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed
    
    private void accionCajaMazo() {
        txtSKU.setEnabled(true);
        txtNombre.setEnabled(true);
        txtEdicion.setEnabled(true);
        txtLinea.setEnabled(true);
        txtStock.setEnabled(true);
        txtPrecio.setEnabled(true);
        txtFechaSalida.setEnabled(true);
        txtDescripcion.setEnabled(true);
        txtCantidadSobre.setEnabled(false);
        txtCantidadMazos.setEnabled(true);
        txtCantidadSobresEspeciales.setEnabled(false);
        txtCartaPromocional.setEnabled(false);
        txtRegaloEspecial.setEnabled(false);
    }
    
    private void accionCajaSobre() {
        txtSKU.setEnabled(true);
        txtNombre.setEnabled(true);
        txtEdicion.setEnabled(true);
        txtLinea.setEnabled(true);
        txtStock.setEnabled(true);
        txtPrecio.setEnabled(true);
        txtFechaSalida.setEnabled(true);
        txtDescripcion.setEnabled(true);
        txtCantidadSobre.setEnabled(true);
        txtCantidadMazos.setEnabled(false);
        txtCantidadSobresEspeciales.setEnabled(false);
        txtCartaPromocional.setEnabled(false);
        txtRegaloEspecial.setEnabled(false);
    }
    
    private void accionCajaEspecial() {
                txtSKU.setEnabled(true);
        txtNombre.setEnabled(true);
        txtEdicion.setEnabled(true);
        txtLinea.setEnabled(true);
        txtStock.setEnabled(true);
        txtPrecio.setEnabled(true);
        txtFechaSalida.setEnabled(true);
        txtDescripcion.setEnabled(true);
        txtCantidadSobre.setEnabled(false);
        txtCantidadMazos.setEnabled(false);
        txtCantidadSobresEspeciales.setEnabled(true);
        txtCartaPromocional.setEnabled(true);
        txtRegaloEspecial.setEnabled(true);

    }
    
    private void limpiarCampos() {
        txtSKU.setText("");
        txtNombre.setText("");
        txtEdicion.setText("");
        txtLinea.setText("");
        txtStock.setText("");
        txtPrecio.setText("");
        txtFechaSalida.setText("");
        txtDescripcion.setText("");
        txtCantidadSobre.setText("");
        txtCantidadMazos.setText("");
        txtCantidadSobresEspeciales.setText("");
        txtCartaPromocional.setText("");
        txtRegaloEspecial.setText("");
        
        txtSKU.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        java.awt.EventQueue.invokeLater(() -> new DistribuidoraVIew().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel lblCantidadMazo;
    private javax.swing.JLabel lblCantidadSobre;
    private javax.swing.JLabel lblCantidadSobreEspecial;
    private javax.swing.JLabel lblCartaPromo;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEdicion;
    private javax.swing.JLabel lblFechaSalida;
    private javax.swing.JLabel lblLinea;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblRegaloExtra;
    private javax.swing.JLabel lblSKU;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTextField txtCantidadMazos;
    private javax.swing.JTextField txtCantidadSobre;
    private javax.swing.JTextField txtCantidadSobresEspeciales;
    private javax.swing.JTextField txtCartaPromocional;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtEdicion;
    private javax.swing.JTextField txtFechaSalida;
    private javax.swing.JTextField txtLinea;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtRegaloEspecial;
    private javax.swing.JTextField txtSKU;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
