/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import static com.mysql.cj.conf.PropertyKey.logger;
import controller.ProductoDAO;
import model.*;
import javax.swing.JOptionPane;
import java.util.logging.Logger;
import java.util.logging.Level;
import utils.FechaUtil;
import validator.*;
/**
 *
 * @author maxan
 */
public class DistribuidoraVIew extends javax.swing.JFrame {
    
    private Producto producto; 
    
    /**
     * Creates new form DistribuidoraVIew
     */
    public DistribuidoraVIew() {
        initComponents();
        this.setSize(696, 650);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        limpiarCampos();
        btnLupa.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSKU = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblEdicion = new javax.swing.JLabel();
        lblLinea = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblFechaSalida = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblCantidadMazo = new javax.swing.JLabel();
        lblCantidadSobre = new javax.swing.JLabel();
        lblRegaloExtra = new javax.swing.JLabel();
        lblCartaPromo = new javax.swing.JLabel();
        lblCantidadSobreEspecial = new javax.swing.JLabel();
        txtSKU = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtEdicion = new javax.swing.JTextField();
        txtLinea = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtFechaSalida = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtCantidadSobre = new javax.swing.JTextField();
        txtCantidadMazos = new javax.swing.JTextField();
        txtCantidadSobresEspeciales = new javax.swing.JTextField();
        txtCartaPromocional = new javax.swing.JTextField();
        txtRegaloEspecial = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        cmbTipo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        cmbOpcion = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnLupa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblSKU.setText("SKU");
        getContentPane().add(lblSKU);
        lblSKU.setBounds(56, 209, 37, 16);

        lblNombre.setText("Nombre");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(50, 240, 80, 30);

        lblEdicion.setText("Edición");
        getContentPane().add(lblEdicion);
        lblEdicion.setBounds(50, 270, 60, 40);

        lblLinea.setText("Linea");
        getContentPane().add(lblLinea);
        lblLinea.setBounds(60, 310, 50, 30);

        lblTipo.setText("Tipo");
        getContentPane().add(lblTipo);
        lblTipo.setBounds(50, 171, 50, 20);

        lblStock.setText("Stock");
        getContentPane().add(lblStock);
        lblStock.setBounds(58, 358, 37, 16);

        lblPrecio.setText("Precio");
        getContentPane().add(lblPrecio);
        lblPrecio.setBounds(50, 390, 60, 30);

        lblFechaSalida.setText("Fecha Salida");
        getContentPane().add(lblFechaSalida);
        lblFechaSalida.setBounds(30, 430, 100, 40);

        lblDescripcion.setText("Descripción");
        getContentPane().add(lblDescripcion);
        lblDescripcion.setBounds(380, 180, 110, 40);

        lblCantidadMazo.setText("Cantidad Mazos");
        getContentPane().add(lblCantidadMazo);
        lblCantidadMazo.setBounds(370, 220, 160, 40);

        lblCantidadSobre.setText("Cantidad Sobre");
        getContentPane().add(lblCantidadSobre);
        lblCantidadSobre.setBounds(370, 260, 140, 40);

        lblRegaloExtra.setText("Regalo Extra");
        getContentPane().add(lblRegaloExtra);
        lblRegaloExtra.setBounds(380, 410, 140, 60);

        lblCartaPromo.setText("Carta Promocional");
        getContentPane().add(lblCartaPromo);
        lblCartaPromo.setBounds(350, 370, 140, 40);

        lblCantidadSobreEspecial.setText("Cantidad Sobres Especial");
        getContentPane().add(lblCantidadSobreEspecial);
        lblCantidadSobreEspecial.setBounds(320, 310, 170, 60);

        txtSKU.addActionListener(this::txtSKUActionPerformed);
        getContentPane().add(txtSKU);
        txtSKU.setBounds(111, 206, 158, 22);

        txtNombre.addActionListener(this::txtNombreActionPerformed);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(111, 241, 158, 22);
        getContentPane().add(txtEdicion);
        txtEdicion.setBounds(111, 281, 158, 22);
        getContentPane().add(txtLinea);
        txtLinea.setBounds(111, 315, 158, 22);
        getContentPane().add(txtStock);
        txtStock.setBounds(111, 355, 158, 22);

        txtPrecio.addActionListener(this::txtPrecioActionPerformed);
        getContentPane().add(txtPrecio);
        txtPrecio.setBounds(111, 395, 158, 22);
        getContentPane().add(txtFechaSalida);
        txtFechaSalida.setBounds(110, 440, 158, 22);

        txtDescripcion.addActionListener(this::txtDescripcionActionPerformed);
        getContentPane().add(txtDescripcion);
        txtDescripcion.setBounds(470, 190, 162, 22);
        getContentPane().add(txtCantidadSobre);
        txtCantidadSobre.setBounds(470, 270, 162, 22);
        getContentPane().add(txtCantidadMazos);
        txtCantidadMazos.setBounds(470, 230, 162, 20);

        txtCantidadSobresEspeciales.addActionListener(this::txtCantidadSobresEspecialesActionPerformed);
        getContentPane().add(txtCantidadSobresEspeciales);
        txtCantidadSobresEspeciales.setBounds(470, 330, 162, 22);

        txtCartaPromocional.addActionListener(this::txtCartaPromocionalActionPerformed);
        getContentPane().add(txtCartaPromocional);
        txtCartaPromocional.setBounds(470, 380, 162, 22);
        getContentPane().add(txtRegaloEspecial);
        txtRegaloEspecial.setBounds(470, 430, 162, 22);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(100, 520, 160, 30);

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Opción", "Caja Mazos", "Caja Sobres", "Caja Especial" }));
        cmbTipo.addActionListener(this::cmbTipoActionPerformed);
        getContentPane().add(cmbTipo);
        cmbTipo.setBounds(111, 172, 158, 22);

        jButton1.setText("Listar");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1);
        jButton1.setBounds(500, 520, 130, 30);

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(this::btnBorrarActionPerformed);
        getContentPane().add(btnBorrar);
        btnBorrar.setBounds(300, 520, 150, 30);

        cmbOpcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Agregar Productos", "Editar Productos", "Borrar Productos" }));
        cmbOpcion.addActionListener(this::cmbOpcionActionPerformed);
        getContentPane().add(cmbOpcion);
        cmbOpcion.setBounds(300, 100, 133, 22);

        jLabel1.setText("Seleccione opción:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 100, 111, 16);

        btnLupa.setText("🔍");
        btnLupa.addActionListener(this::btnLupaActionPerformed);
        getContentPane().add(btnLupa);
        btnLupa.setBounds(280, 200, 60, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("DISTRIBUIDORA TCG BOLA DE FUEGO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 20, 570, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        if ("Agregar Productos".equals(cmbOpcion.getSelectedItem())) {
            
            String tipoSeleccionado = cmbTipo.getSelectedItem().toString();
            producto = null; 
            
            boolean isTipoValido = false;
            try {
                if ("Caja Sobres".equals(tipoSeleccionado)) {
                    producto = new CajaSobre(0, "", "", "", "Caja Sobres", 0, 0, "", "", ""); 
                } else if ("Caja Mazos".equals(tipoSeleccionado)) {
                    producto = new CajaMazo(0, "", "", "", "Caja Mazos", 0, 0, "", "", "");
                } else if ("Caja Especial".equals(tipoSeleccionado)) {
                    producto = new CajaEspecial(0, "", "", "", "", "", "Caja Especial", 0, 0, "", "", "");
                } else {
                    throw new Exception("Debe seleccionar un Tipo de Producto válido.");
                }
                isTipoValido = true;
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            
            
            
            boolean isSKUValido = false;
            try {
                String sku = txtSKU.getText().trim();
                ValidadorSku.validarSku(txtSKU.getText());
                producto.setSku(txtSKU.getText());
                isSKUValido = true;
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Error en SKU: " + e.getMessage());
            }
            
            
            boolean isNombreValido = false;
            
            try {
                ValidadorGeneral.validarTamanioTexto(txtNombre.getText(), 0, 50, "NOMBRE");
                ValidadorGeneral.validarTextoVacio(txtNombre.getText(), "NOMBRE");
                producto.setNombre(txtNombre.getText());
                isNombreValido = true;
            } catch (Exception Ex){
                JOptionPane.showMessageDialog(this, Ex.getMessage());
            }

            boolean isEdicionValido = false;
            try {
                ValidadorGeneral.validarTamanioTexto(txtEdicion.getText(), 0, 50, "EDICION");
                ValidadorGeneral.validarTextoVacio(txtEdicion.getText(), "EDICION");
                producto.setEdicion(txtEdicion.getText());
                isEdicionValido = true;
            } catch (Exception Ex){
                JOptionPane.showMessageDialog(this, Ex.getMessage());
            }
           

            boolean isLineaValido = false;
            try {
                ValidadorGeneral.validarTamanioTexto(txtLinea.getText(), 0, 50, "LINEA");
                producto.setLinea(txtLinea.getText());
                isLineaValido = true;
            } catch (Exception Ex){
                JOptionPane.showMessageDialog(this, Ex.getMessage());
            }

            boolean isStockValido = false;
            try {
                ValidadorGeneral.validarTamanioTexto(txtStock.getText(), 0, 4, "STOCK");
                ValidadorGeneral.validarTextoVacio(txtStock.getText(), "STOCK");
                ValidadorGeneral.validarStock(txtStock.getText(), "STOCK");
                producto.setStock(Integer.parseInt(txtStock.getText()));
                isStockValido = true;
            } catch (Exception Ex){
                JOptionPane.showMessageDialog(this, Ex.getMessage());
            }

            boolean isPrecioValido = false;
            try {
                ValidadorGeneral.validarTamanioTexto(txtPrecio.getText(), 0, 8, "PRECIO");
                ValidadorGeneral.validarTextoVacio(txtPrecio.getText(), "PRECIO");
                ValidadorGeneral.validarEnteroPositivo(txtPrecio.getText(), "PRECIO");
                producto.setPrecio(Integer.parseInt(txtPrecio.getText()));
                isPrecioValido = true;
            } catch (Exception Ex){
                JOptionPane.showMessageDialog(this, Ex.getMessage());
            }

            boolean isFechaSalidaValido = false;
            String fechaTxt = txtFechaSalida.getText().trim();
            
            if (fechaTxt.isEmpty()) {
                producto.setFechaSalida(null); 
                isFechaSalidaValido = true;
            } else {
            try {
                java.util.Date fechaCl = FechaUtil.textoADate(txtFechaSalida.getText(), FechaUtil.DD_MM_YYYY);
                String fechaSQL = FechaUtil.DateATexto(fechaCl, "yyyy-MM-dd");
                producto.setFechaSalida(fechaSQL);
                isFechaSalidaValido = true;
            } catch (java.text.ParseException e) {
                JOptionPane.showMessageDialog(this, "Error en Fecha: Use el formato " + FechaUtil.DD_MM_YYYY + " (ej: 25-12-2023)");
            } catch (Exception Ex){
                JOptionPane.showMessageDialog(this, Ex.getMessage());
            }
            }

            boolean isDescripcionValido = false;
            try {
                ValidadorGeneral.validarTamanioTexto(txtDescripcion.getText(), 0, 80, "DESCRIPCION");
                producto.setDescripcion(txtDescripcion.getText());
                isDescripcionValido = true;
            } catch (Exception Ex){
                JOptionPane.showMessageDialog(this, Ex.getMessage());
            }


            boolean isCantidadSobreValido = false;
            boolean isCantidadMazoValido = false;
            boolean isCantidadSobreEspecialValido = false;
            boolean isCartaPromoValido = false;
            boolean isRegaloExtraValido = false;


            if (producto instanceof CajaSobre) {
                try {
                    ValidadorGeneral.validarEnteroPositivo(txtCantidadSobre.getText(), "CANTIDAD_SOBRE");
                    ValidadorGeneral.validarTamanioTexto(txtCantidadSobre.getText(), 0, 4, "CANTIDAD_SOBRE");
                    ValidadorGeneral.validarTextoVacio(txtCantidadSobre.getText(), "CANTIDAD_SOBRE");
                    ((CajaSobre) producto).setCantidadPorCaja(Integer.parseInt(txtCantidadSobre.getText()));
                    isCantidadSobreValido = true;
                } catch (Exception Ex) {
                    JOptionPane.showMessageDialog(this, Ex.getMessage());
                }
            }


            else if (producto instanceof CajaMazo) {
                try {
                    ValidadorGeneral.validarTamanioTexto(txtCantidadMazos.getText(), 0, 4, "CANTIDAD_MAZO");
                    ValidadorGeneral.validarEnteroPositivo(txtCantidadMazos.getText(), "CANTIDAD_MAZO");
                    ValidadorGeneral.validarTextoVacio(txtCantidadMazos.getText(), "CANTIDAD_MAZO");
                    ((CajaMazo) producto).setCantidadPorCaja(Integer.parseInt(txtCantidadMazos.getText()));
                    isCantidadMazoValido = true;
                } catch (Exception Ex) {
                    JOptionPane.showMessageDialog(this, Ex.getMessage());
                }
            }


            else if (producto instanceof CajaEspecial) {
                try {
                    ValidadorGeneral.validarEnteroPositivo(txtCantidadSobresEspeciales.getText(), "CANTIDAD_SOBRE_ESPECIAL");
                    ValidadorGeneral.validarTamanioTexto(txtCantidadSobresEspeciales.getText(), 0, 4, "CANTIDAD_SOBRE_ESPECIAL");
                    ValidadorGeneral.validarTextoVacio(txtCantidadSobresEspeciales.getText(), "CANTIDAD_SOBRE_ESPECIAL");
                    ((CajaEspecial) producto).setCantidadSobres(Integer.parseInt(txtCantidadSobresEspeciales.getText()));
                    isCantidadSobreEspecialValido = true;
                } catch (Exception Ex) {
                    JOptionPane.showMessageDialog(this, Ex.getMessage());
                }

                try {
                    ValidadorGeneral.validarTamanioTexto(txtCartaPromocional.getText(), 0, 80, "CARTA_PROMO");
                    ValidadorGeneral.validarTextoVacio(txtCartaPromocional.getText(), "CARTA_PROMO");
                    ((CajaEspecial) producto).setCartasPromo(txtCartaPromocional.getText());
                    isCartaPromoValido = true;
                } catch (Exception Ex) {
                    JOptionPane.showMessageDialog(this, Ex.getMessage());
                }

                try {
                    ValidadorGeneral.validarTamanioTexto(txtRegaloEspecial.getText(), 0, 80, "REGALO_EXTRA");
                    ValidadorGeneral.validarTextoVacio(txtRegaloEspecial.getText(), "REGALO_EXTRA");
                    ((CajaEspecial) producto).setRegaloExtra(txtRegaloEspecial.getText());
                    isRegaloExtraValido = true;
                } catch (Exception Ex) {
                    JOptionPane.showMessageDialog(this, Ex.getMessage());
                }
            }


            boolean isTipoProductoValido = false;
            if (producto instanceof CajaSobre) {
                isTipoProductoValido = isCantidadSobreValido;
            } else if (producto instanceof CajaMazo) {
                isTipoProductoValido = isCantidadMazoValido;
            } else if (producto instanceof CajaEspecial) {
                isTipoProductoValido = isCantidadSobreEspecialValido && isCartaPromoValido && isRegaloExtraValido;
            }


            if (isSKUValido && isNombreValido && isEdicionValido && isLineaValido && isTipoValido
               && isStockValido && isPrecioValido && isFechaSalidaValido 
               && isDescripcionValido && isTipoProductoValido) {

                ProductoDAO dao = new ProductoDAO();
                boolean resultado = dao.insertar(producto);

                System.out.println("actualizar -> " + resultado);

            if (resultado) {
                    JOptionPane.showMessageDialog(this, "El Producto se agregó correctamente");
                    limpiarCampos();

                    this.producto = null;
                } else {
                    JOptionPane.showMessageDialog(this, "Error al agregar el producto");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Por favor corrija los errores en los campos antes de guardar");
            }
    }
    
    else if ("Editar Productos".equals(cmbOpcion.getSelectedItem())) {
        
        if (this.producto == null) {
        JOptionPane.showMessageDialog(this, "Primero debe buscar el producto con la Lupa (ingrese SKU) para poder editarlo.");
        return;
        }
        
        
        boolean isNombreValido = false;
        try {
            ValidadorGeneral.validarTamanioTexto(txtNombre.getText(), 0, 50, "NOMBRE");
            ValidadorGeneral.validarTextoVacio(txtNombre.getText(), "NOMBRE");
            producto.setNombre(txtNombre.getText());
            isNombreValido = true;
        } catch (Exception Ex){
            JOptionPane.showMessageDialog(this, "Error en nombre: " + Ex.getMessage());
        }
        
        boolean isEdicionValido = false;
        try {
            ValidadorGeneral.validarTamanioTexto(txtEdicion.getText(), 0, 50, "EDICION");
            ValidadorGeneral.validarTextoVacio(txtEdicion.getText(), "EDICION");
            producto.setEdicion(txtEdicion.getText());
            isEdicionValido = true;
        } catch (Exception Ex){
            JOptionPane.showMessageDialog(this, "Error en edición: " + Ex.getMessage());
        }
        

        boolean isLineaValido = false;
        try {
            ValidadorGeneral.validarTamanioTexto(txtLinea.getText(), 0, 50, "LINEA");
            producto.setLinea(txtLinea.getText());
            isLineaValido = true;
        } catch (Exception Ex){
            JOptionPane.showMessageDialog(this, "Error en línea: " + Ex.getMessage());
        }
        
        boolean isStockValido = false;
        try {
            ValidadorGeneral.validarTextoVacio(txtStock.getText(), "STOCK");
            ValidadorGeneral.validarTamanioTexto(txtStock.getText(), 0, 4, "STOCK");
            ValidadorGeneral.validarStock(txtStock.getText(), "STOCK");
            producto.setStock(Integer.parseInt(txtStock.getText()));
            isStockValido = true;
        } catch (Exception Ex){
            JOptionPane.showMessageDialog(this, "Error en stock: " + Ex.getMessage());
        }
        
        boolean isPrecioValido = false;
        try {
            ValidadorGeneral.validarTextoVacio(txtPrecio.getText(), "PRECIO");
            ValidadorGeneral.validarTamanioTexto(txtPrecio.getText(), 0, 8, "PRECIO");
            ValidadorGeneral.validarEnteroPositivo(txtPrecio.getText(), "PRECIO");
            producto.setPrecio(Integer.parseInt(txtPrecio.getText()));
            isPrecioValido = true;
        } catch (Exception Ex){
            JOptionPane.showMessageDialog(this, "Error en precio: " + Ex.getMessage());
        }
        
        boolean isFechaSalidaValido = false;
        String fechaTxt = txtFechaSalida.getText().trim();   
        if (fechaTxt.isEmpty()) {
                producto.setFechaSalida(null); 
                isFechaSalidaValido = true;
        }else {
        try {
                java.util.Date fechaCl = FechaUtil.textoADate(txtFechaSalida.getText(), FechaUtil.DD_MM_YYYY);
                String fechaSQL = FechaUtil.DateATexto(fechaCl, "yyyy-MM-dd");
                producto.setFechaSalida(fechaSQL);
                isFechaSalidaValido = true;  
            } catch (java.text.ParseException e) {
                JOptionPane.showMessageDialog(this, "Error en Fecha: Use el formato " + FechaUtil.DD_MM_YYYY);
            } catch (Exception Ex){
                JOptionPane.showMessageDialog(this, Ex.getMessage());
            }
        }
        
        boolean isDescripcionValido = false;
        try {
            ValidadorGeneral.validarTamanioTexto(txtDescripcion.getText(), 0, 80, "DESCRIPCION");
            producto.setDescripcion(txtDescripcion.getText());
            isDescripcionValido = true;
        } catch (Exception Ex){
            JOptionPane.showMessageDialog(this, "Error en descripción: " + Ex.getMessage());
        }
        
       
        boolean isCantidadSobreValido = false;
        boolean isCantidadMazoValido = false;
        boolean isCantidadSobreEspecialValido = false;
        boolean isCartaPromoValido = false;
        boolean isRegaloExtraValido = false;
        
        
        if (producto instanceof CajaSobre) {
            try {
                ValidadorGeneral.validarEnteroPositivo(txtCantidadSobre.getText(), "CANTIDAD_SOBRE");
                ValidadorGeneral.validarTextoVacio(txtCantidadSobre.getText(), "CANTIDAD_SOBRE");
                ValidadorGeneral.validarTamanioTexto(txtCantidadSobre.getText(), 0, 4, "CANTIDAD_SOBRE");
                ((CajaSobre) producto).setCantidadPorCaja(Integer.parseInt(txtCantidadSobre.getText()));
                isCantidadSobreValido = true;
            } catch (Exception Ex) {
                JOptionPane.showMessageDialog(this, "Error en cantidad sobre: " + Ex.getMessage());
            }
        }
        
      
        else if (producto instanceof CajaMazo) {
            try {
                ValidadorGeneral.validarTamanioTexto(txtCantidadMazos.getText(), 0, 4, "CANTIDAD_MAZO");
                ValidadorGeneral.validarTextoVacio(txtCantidadMazos.getText(), "CANTIDAD_MAZO");
                ValidadorGeneral.validarEnteroPositivo(txtCantidadMazos.getText(), "CANTIDAD_MAZO");
                ((CajaMazo) producto).setCantidadPorCaja(Integer.parseInt(txtCantidadMazos.getText()));
                isCantidadMazoValido = true;
            } catch (Exception Ex) {
                JOptionPane.showMessageDialog(this, "Error en cantidad mazo: " + Ex.getMessage());
            }
        }
        
        
        else if (producto instanceof CajaEspecial) {
            try {
                ValidadorGeneral.validarNumeroEntero(txtCantidadSobresEspeciales.getText(), "CANTIDAD_SOBRE_ESPECIAL");
                ValidadorGeneral.validarTamanioTexto(txtCantidadSobresEspeciales.getText(), 0, 4, "CANTIDAD_SOBRE_ESPECIAL");
                ValidadorGeneral.validarTextoVacio(txtCantidadSobresEspeciales.getText(), "CANTIDAD_SOBRE_ESPECIAL");
                ((CajaEspecial) producto).setCantidadSobres(Integer.parseInt(txtCantidadSobresEspeciales.getText()));
                isCantidadSobreEspecialValido = true;
            } catch (Exception Ex) {
                JOptionPane.showMessageDialog(this, "Error en cantidad sobres especiales: " + Ex.getMessage());
            }
            
            try {
                ValidadorGeneral.validarTamanioTexto(txtCartaPromocional.getText(), 0, 80, "CARTA_PROMO");
                ValidadorGeneral.validarTextoVacio(txtCartaPromocional.getText(), "CARTA_PROMO");
                ((CajaEspecial) producto).setCartasPromo(txtCartaPromocional.getText());
                isCartaPromoValido = true;
            } catch (Exception Ex) {
                JOptionPane.showMessageDialog(this, "Error en carta promocional: " + Ex.getMessage());
            }
            
            try {
                ValidadorGeneral.validarTamanioTexto(txtRegaloEspecial.getText(), 0, 80, "REGALO_EXTRA");
                ValidadorGeneral.validarTextoVacio(txtRegaloEspecial.getText(), "REGALO_EXTRA");
                ((CajaEspecial) producto).setRegaloExtra(txtRegaloEspecial.getText());
                isRegaloExtraValido = true;
            } catch (Exception Ex) {
                JOptionPane.showMessageDialog(this, "Error en regalo extra: " + Ex.getMessage());
            }
        }
        
        
       
        boolean isTipoProductoValido = false;
        if (producto instanceof CajaSobre) {
            isTipoProductoValido = isCantidadSobreValido;
        } else if (producto instanceof CajaMazo) {
            isTipoProductoValido = isCantidadMazoValido;
        } else if (producto instanceof CajaEspecial) {
            isTipoProductoValido = isCantidadSobreEspecialValido && isCartaPromoValido && isRegaloExtraValido;
        }
        
    
        if (isNombreValido && isEdicionValido && isLineaValido
           && isStockValido && isPrecioValido && isFechaSalidaValido 
           && isDescripcionValido && isTipoProductoValido) {
            
            ProductoDAO dao = new ProductoDAO();
            boolean resultado = dao.actualizarProducto(producto);

            System.out.println("actualizar -> " + resultado);

            if (resultado) {
                JOptionPane.showMessageDialog(this, "El Producto se modificó correctamente");
                limpiarCampos();
   
                this.producto = null;
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar en la Base de Datos");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor corrija los errores en los campos antes de guardar");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed
 }
    private void txtSKUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSKUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSKUActionPerformed

    private void txtCartaPromocionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCartaPromocionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCartaPromocionalActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
          if ("Caja Mazos".equals(cmbTipo.getSelectedItem())){
              accionCajaMazo();
          }
          
          if ("Caja Sobres".equals(cmbTipo.getSelectedItem())){
              accionCajaSobre();
          }
          
          if ("Caja Especial".equals(cmbTipo.getSelectedItem())){
              accionCajaEspecial();
          }
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        FormularioListarProducto formListarProducto = new FormularioListarProducto();
        formListarProducto.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        String sku = txtSKU.getText().trim();

    if (sku.isEmpty()) {
        JOptionPane.showMessageDialog(rootPane, "Debe ingresar un SKU para borrar.");
        return;
    }
    int confirm = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar el producto " + sku + "?");
    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    ProductoDAO dao = new ProductoDAO();
    boolean resultado = dao.eliminarProducto(sku); 
    
    if(resultado){
        JOptionPane.showMessageDialog(rootPane, "Producto eliminado");            
        limpiarCampos();
        this.producto = null; 
    } else {
        JOptionPane.showMessageDialog(rootPane, "El producto no se pudo eliminar (o no existe)");                        
    }
        
              
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNombreActionPerformed

    private void cmbOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOpcionActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
        
        String opcion = (String) cmbOpcion.getSelectedItem();
        
        if ("Editar Productos".equals(opcion)) {
            ocultarTodoMenosSKU();
            btnLupa.setVisible(true);
            btnGuardar.setText("Guardar Cambios");
            btnGuardar.setVisible(true);
            btnBorrar.setVisible(false);
            cmbTipo.setEnabled(false);
        } 
        else if ("Agregar Productos".equals(opcion)) {
            mostrarElementosGenerales();
            btnLupa.setVisible(false);
            lblTipo.setVisible(true);
            cmbTipo.setVisible(true);
            cmbTipo.setEnabled(true);
            btnGuardar.setText("Guardar");
            btnGuardar.setVisible(true);
            btnBorrar.setVisible(false);
        } 
        else if ("Borrar Productos".equals(opcion)) {
            mostrarElementosGenerales();
            btnLupa.setVisible(true); 
            btnGuardar.setVisible(false);
            btnBorrar.setVisible(true);
            cmbTipo.setEnabled(false);
        }
        else {
            btnLupa.setVisible(false);
        }
        
    }//GEN-LAST:event_cmbOpcionActionPerformed

    private void btnLupaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLupaActionPerformed

    String skuBuscado = txtSKU.getText().trim();

    if (skuBuscado.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Primero debe ingresar un SKU para buscar el producto",
            "Error",
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    ProductoDAO dao = new ProductoDAO();
    Producto p = dao.buscarPorSku(skuBuscado);

    if (p != null) {
        this.producto = p;
    } else {
        JOptionPane.showMessageDialog(this, "Producto no encontrado");
        this.producto = null;
        return;
    }

    txtNombre.setText(p.getNombre());
    txtEdicion.setText(p.getEdicion());
    txtLinea.setText(p.getLinea());
    txtStock.setText("" + p.getStock());
    txtPrecio.setText("" + p.getPrecio());
    try {
        java.util.Date fechaSql = FechaUtil.textoADate(p.getFechaSalida(), "yyyy-MM-dd");
        String fechaCl = FechaUtil.DateATexto(fechaSql, FechaUtil.DD_MM_YYYY);
        txtFechaSalida.setText(fechaCl);
    
    }catch (Exception e) {
        txtFechaSalida.setText(p.getFechaSalida());
    }
    txtDescripcion.setText(p.getDescripcion());
    cmbTipo.setEnabled(false);

    if (p instanceof CajaMazo){
        txtCantidadMazos.setText("" + ((CajaMazo) p).getCantidadPorCaja());
        cmbTipo.setSelectedItem("Caja Mazos");
        accionCajaMazo();
    }else if (p instanceof CajaSobre){
        txtCantidadSobre.setText("" + ((CajaSobre) p).getCantidadPorCaja());
        cmbTipo.setSelectedItem("Caja Sobres");
        accionCajaSobre();
    }else if (p instanceof CajaEspecial){
        txtCantidadSobresEspeciales.setText("" + ((CajaEspecial) p).getCantidadSobres());
        txtCartaPromocional.setText(((CajaEspecial) p).getCartasPromo());
        txtRegaloEspecial.setText(((CajaEspecial) p).getRegaloExtra());
        cmbTipo.setSelectedItem("Caja Especial");
        accionCajaEspecial();
    }

    cmbTipo.setEnabled(false);

    
            

    }//GEN-LAST:event_btnLupaActionPerformed

    private void txtCantidadSobresEspecialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadSobresEspecialesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadSobresEspecialesActionPerformed
    
      private void accionCajaMazo() {
        mostrarElementosGenerales();
          //enable txt
        txtSKU.setEnabled(true);
        txtNombre.setEnabled(true);
        txtEdicion.setEnabled(true);
        txtLinea.setEnabled(true);
        txtStock.setEnabled(true);
        txtPrecio.setEnabled(true);
        txtFechaSalida.setEnabled(true);
        txtDescripcion.setEnabled(true);
        txtCantidadSobre.setEnabled(false);
        txtCantidadMazos.setEnabled(true);
        txtCantidadSobresEspeciales.setEnabled(false);
        txtCartaPromocional.setEnabled(false);
        txtRegaloEspecial.setEnabled(false);
        //visible txt
        txtSKU.setVisible(true);
        txtNombre.setVisible(true);
        txtEdicion.setVisible(true);
        txtLinea.setVisible(true);
        txtStock.setVisible(true);
        txtPrecio.setVisible(true);
        txtFechaSalida.setVisible(true);
        txtDescripcion.setVisible(true);
        txtCantidadSobre.setVisible(false);
        txtCantidadMazos.setVisible(true);
        txtCantidadSobresEspeciales.setVisible(false);
        txtCartaPromocional.setVisible(false);
        txtRegaloEspecial.setVisible(false);
        lblCantidadSobre.setVisible(false);
        lblCantidadMazo.setVisible(true);
        lblCantidadSobreEspecial.setVisible(false);
        lblCartaPromo.setVisible(false);
        lblRegaloExtra.setVisible(false);
        this.setLocationRelativeTo(null);
        
    }
    
    private void accionCajaSobre() {
        mostrarElementosGenerales();
        //enable txt
        txtSKU.setEnabled(true);
        txtNombre.setEnabled(true);
        txtEdicion.setEnabled(true);
        txtLinea.setEnabled(true);
        txtStock.setEnabled(true);
        txtPrecio.setEnabled(true);
        txtFechaSalida.setEnabled(true);
        txtDescripcion.setEnabled(true);
        txtCantidadSobre.setEnabled(true);
        txtCantidadMazos.setEnabled(false);
        txtCantidadSobresEspeciales.setEnabled(false);
        txtCartaPromocional.setEnabled(false);
        txtRegaloEspecial.setEnabled(false);
        //visible txt
        txtSKU.setVisible(true);
        txtNombre.setVisible(true);
        txtEdicion.setVisible(true);
        txtLinea.setVisible(true);
        txtStock.setVisible(true);
        txtPrecio.setVisible(true);
        txtFechaSalida.setVisible(true);
        txtDescripcion.setVisible(true);
        txtCantidadSobre.setVisible(true);
        txtCantidadMazos.setVisible(false);
        txtCantidadSobresEspeciales.setVisible(false);
        txtCartaPromocional.setVisible(false);
        txtRegaloEspecial.setVisible(false);
        lblCantidadSobre.setVisible(true);
        lblCantidadMazo.setVisible(false);
        lblCantidadSobreEspecial.setVisible(false);
        lblCartaPromo.setVisible(false);
        lblRegaloExtra.setVisible(false);
        this.setLocationRelativeTo(null);
        
    }
    
    private void accionCajaEspecial() {
        mostrarElementosGenerales();
        //enable txt
        txtSKU.setEnabled(true);
        txtNombre.setEnabled(true);
        txtEdicion.setEnabled(true);
        txtLinea.setEnabled(true);
        txtStock.setEnabled(true);
        txtPrecio.setEnabled(true);
        txtFechaSalida.setEnabled(true);
        txtDescripcion.setEnabled(true);
        txtCantidadSobre.setEnabled(false);
        txtCantidadMazos.setEnabled(false);
        txtCantidadSobresEspeciales.setEnabled(true);
        txtCartaPromocional.setEnabled(true);
        txtRegaloEspecial.setEnabled(true);
        //visible txt
        txtSKU.setVisible(true);
        txtNombre.setVisible(true);
        txtEdicion.setVisible(true);
        txtLinea.setVisible(true);
        txtStock.setVisible(true);
        txtPrecio.setVisible(true);
        txtFechaSalida.setVisible(true);
        txtDescripcion.setVisible(true);
        txtCantidadSobre.setVisible(false);
        txtCantidadMazos.setVisible(false);
        txtCantidadSobresEspeciales.setVisible(true);
        txtCartaPromocional.setVisible(true);
        txtRegaloEspecial.setVisible(true);
        lblCantidadSobre.setVisible(false);
        lblCantidadMazo.setVisible(false);
        lblCantidadSobreEspecial.setVisible(true);
        lblCartaPromo.setVisible(true);
        lblRegaloExtra.setVisible(true);
        this.setLocationRelativeTo(null);

    }
    private void ocultarTodoMenosSKU() {
        lblNombre.setVisible(false);
        lblEdicion.setVisible(false);
        lblLinea.setVisible(false);
        lblTipo.setVisible(false);
        lblStock.setVisible(false);
        lblPrecio.setVisible(false);
        lblFechaSalida.setVisible(false);
        lblDescripcion.setVisible(false);

        txtNombre.setVisible(false);
        txtEdicion.setVisible(false);
        txtLinea.setVisible(false);
        cmbTipo.setVisible(false); 
        txtStock.setVisible(false);
        txtPrecio.setVisible(false);
        txtFechaSalida.setVisible(false);
        txtDescripcion.setVisible(false);

        lblCantidadMazo.setVisible(false);
        lblCantidadSobre.setVisible(false);
        lblRegaloExtra.setVisible(false);
        lblCartaPromo.setVisible(false);
        lblCantidadSobreEspecial.setVisible(false);
        
        txtCantidadMazos.setVisible(false);
        txtCantidadSobre.setVisible(false);
        txtRegaloEspecial.setVisible(false);
        txtCartaPromocional.setVisible(false);
        txtCantidadSobresEspeciales.setVisible(false);
        lblSKU.setVisible(true);
        txtSKU.setVisible(true);
        txtSKU.setEnabled(true);
    }
    private void mostrarElementosGenerales() {
        lblNombre.setVisible(true);
        lblEdicion.setVisible(true);
        lblLinea.setVisible(true);
        lblTipo.setVisible(true);
        lblStock.setVisible(true);
        lblPrecio.setVisible(true);
        lblFechaSalida.setVisible(true);
        lblDescripcion.setVisible(true);
        txtNombre.setVisible(true);
        txtEdicion.setVisible(true);
        txtLinea.setVisible(true);
        txtStock.setVisible(true);
        txtPrecio.setVisible(true);
        txtFechaSalida.setVisible(true);
        txtDescripcion.setVisible(true);
        cmbTipo.setVisible(true);
    }
    private void limpiarCampos() {
        txtSKU.setText("");
        txtNombre.setText("");
        txtEdicion.setText("");
        txtLinea.setText("");
        txtStock.setText("");
        txtPrecio.setText("");
        txtFechaSalida.setText("");
        txtDescripcion.setText("");
        txtCantidadSobre.setText("");
        txtCantidadMazos.setText("");
        txtCantidadSobresEspeciales.setText("");
        txtCartaPromocional.setText("");
        txtRegaloEspecial.setText("");
        
        txtSKU.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        java.awt.EventQueue.invokeLater(() -> new DistribuidoraVIew().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLupa;
    private javax.swing.JComboBox<String> cmbOpcion;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCantidadMazo;
    private javax.swing.JLabel lblCantidadSobre;
    private javax.swing.JLabel lblCantidadSobreEspecial;
    private javax.swing.JLabel lblCartaPromo;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEdicion;
    private javax.swing.JLabel lblFechaSalida;
    private javax.swing.JLabel lblLinea;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblRegaloExtra;
    private javax.swing.JLabel lblSKU;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTextField txtCantidadMazos;
    private javax.swing.JTextField txtCantidadSobre;
    private javax.swing.JTextField txtCantidadSobresEspeciales;
    private javax.swing.JTextField txtCartaPromocional;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtEdicion;
    private javax.swing.JTextField txtFechaSalida;
    private javax.swing.JTextField txtLinea;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtRegaloEspecial;
    private javax.swing.JTextField txtSKU;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
