/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import static com.mysql.cj.conf.PropertyKey.logger;
import controller.ProductoDAO;
import model.*;
import javax.swing.JOptionPane;
import java.util.logging.Logger;
import java.util.logging.Level;
import validator.*;
/**
 *
 * @author maxan
 */
public class DistribuidoraVIew extends javax.swing.JFrame {
    
    private Producto producto; 
    
    /**
     * Creates new form DistribuidoraVIew
     */
    public DistribuidoraVIew() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        limpiarCampos();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSKU = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblEdicion = new javax.swing.JLabel();
        lblLinea = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblFechaSalida = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblCantidadMazo = new javax.swing.JLabel();
        lblCantidadSobre = new javax.swing.JLabel();
        lblRegaloExtra = new javax.swing.JLabel();
        lblCartaPromo = new javax.swing.JLabel();
        lblCantidadSobreEspecial = new javax.swing.JLabel();
        txtSKU = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtEdicion = new javax.swing.JTextField();
        txtLinea = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtFechaSalida = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtCantidadSobre = new javax.swing.JTextField();
        txtCantidadMazos = new javax.swing.JTextField();
        txtCantidadSobresEspeciales = new javax.swing.JTextField();
        txtCartaPromocional = new javax.swing.JTextField();
        txtRegaloEspecial = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        cmbTipo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        cmbOpcion = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnLupa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSKU.setText("SKU");

        lblNombre.setText("Nombre");

        lblEdicion.setText("Edición");

        lblLinea.setText("Linea");

        lblTipo.setText("Tipo");

        lblStock.setText("Stock");

        lblPrecio.setText("Precio");

        lblFechaSalida.setText("Fecha Salida");

        lblDescripcion.setText("Descripción");

        lblCantidadMazo.setText("Cantidad Mazos");

        lblCantidadSobre.setText("Cantidad Sobre");

        lblRegaloExtra.setText("Regalo Extra");

        lblCartaPromo.setText("Carta Promocional");

        lblCantidadSobreEspecial.setText("Cantidad Sobres Especial");

        txtSKU.addActionListener(this::txtSKUActionPerformed);

        txtNombre.addActionListener(this::txtNombreActionPerformed);

        txtPrecio.addActionListener(this::txtPrecioActionPerformed);

        txtDescripcion.addActionListener(this::txtDescripcionActionPerformed);

        txtCartaPromocional.addActionListener(this::txtCartaPromocionalActionPerformed);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Opción", "Caja Mazos", "Caja Sobres", "Caja Especial" }));
        cmbTipo.addActionListener(this::cmbTipoActionPerformed);

        jButton1.setText("Listar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(this::btnBorrarActionPerformed);

        cmbOpcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Agregar Productos", "Editar Productos", "Borrar Productos" }));
        cmbOpcion.addActionListener(this::cmbOpcionActionPerformed);

        jLabel1.setText("Seleccione opción:");

        btnLupa.setText("🔍");
        btnLupa.addActionListener(this::btnLupaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(52, 52, 52)
                                                .addComponent(lblEdicion))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(58, 58, 58)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblStock, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblPrecio)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(56, 56, 56)
                                                .addComponent(lblSKU, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(lblFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(20, 20, 20)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEdicion)
                                            .addComponent(txtLinea, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPrecio)
                                            .addComponent(txtStock, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSKU, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                            .addComponent(txtFechaSalida)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLupa)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblDescripcion)
                                    .addGap(78, 78, 78)
                                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblRegaloExtra)
                                            .addGap(108, 108, 108))
                                        .addComponent(lblCartaPromo, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(139, 139, 139)
                                        .addComponent(txtCantidadMazos, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCantidadMazo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCantidadSobre)
                                        .addGap(58, 58, 58)
                                        .addComponent(txtCantidadSobre, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnBorrar)
                                        .addComponent(lblCantidadSobreEspecial))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCantidadSobresEspeciales)
                                        .addComponent(txtRegaloEspecial)
                                        .addComponent(txtCartaPromocional, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSKU)
                    .addComponent(txtSKU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadMazos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantidadMazo)
                    .addComponent(btnLupa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEdicion)
                            .addComponent(txtEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLinea)
                            .addComponent(txtLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStock)
                            .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCantidadSobre)
                            .addComponent(txtCantidadSobre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCantidadSobreEspecial)
                            .addComponent(txtCantidadSobresEspeciales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCartaPromo)
                            .addComponent(txtCartaPromocional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRegaloEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRegaloExtra))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaSalida)
                            .addComponent(txtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnBorrar))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        if ("Agregar Productos".equals(cmbOpcion.getSelectedItem())) {
            
            String tipoSeleccionado = cmbTipo.getSelectedItem().toString();
            producto = null; 
            
            boolean isTipoValido = false;
            try {
                if ("Caja Sobres".equals(tipoSeleccionado)) {
                    producto = new CajaSobre(0, "", "", "", "Caja Sobres", 0, 0, "", "", ""); 
                } else if ("Caja Mazos".equals(tipoSeleccionado)) {
                    producto = new CajaMazo(0, "", "", "", "Caja Mazos", 0, 0, "", "", "");
                } else if ("Caja Especial".equals(tipoSeleccionado)) {
                    producto = new CajaEspecial(0, "", "", "", "", "", "Caja Especial", 0, 0, "", "", "");
                } else {
                    throw new Exception("Debe seleccionar un Tipo de Producto válido.");
                }
                isTipoValido = true;
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            
            
            
            boolean isSKUValido = false;
            try {
                String sku = txtSKU.getText().trim();
                ValidadorSku.validarSku(txtSKU.getText());
                producto.setSku(txtSKU.getText());
                isSKUValido = true;
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Error en SKU: " + e.getMessage());
            }
            
            
            boolean isNombreValido = false;
            
            try {
                ValidadorGeneral.validarTamanioTexto(txtNombre.getText(), 0, 50, "NOMBRE");
                ValidadorGeneral.validarTextoVacio(txtNombre.getText(), "NOMBRE");
                producto.setNombre(txtNombre.getText());
                isNombreValido = true;
            } catch (Exception Ex){
                JOptionPane.showMessageDialog(this, Ex.getMessage());
            }

            boolean isEdicionValido = false;
            try {
                ValidadorGeneral.validarTamanioTexto(txtEdicion.getText(), 0, 50, "EDICION");
                ValidadorGeneral.validarTextoVacio(txtEdicion.getText(), "EDICION");
                producto.setEdicion(txtEdicion.getText());
                isEdicionValido = true;
            } catch (Exception Ex){
                JOptionPane.showMessageDialog(this, Ex.getMessage());
            }
           

            boolean isLineaValido = false;
            try {
                ValidadorGeneral.validarTamanioTexto(txtLinea.getText(), 0, 50, "LINEA");
                ValidadorGeneral.validarTextoVacio(txtLinea.getText(), "LINEA");
                producto.setLinea(txtLinea.getText());
                isLineaValido = true;
            } catch (Exception Ex){
                JOptionPane.showMessageDialog(this, Ex.getMessage());
            }

            boolean isStockValido = false;
            try {
                ValidadorGeneral.validarTamanioTexto(txtStock.getText(), 0, 4, "STOCK");
                ValidadorGeneral.validarTextoVacio(txtStock.getText(), "STOCK");
                producto.setStock(Integer.parseInt(txtStock.getText()));
                isStockValido = true;
            } catch (Exception Ex){
                JOptionPane.showMessageDialog(this, Ex.getMessage());
            }

            boolean isPrecioValido = false;
            try {
                ValidadorGeneral.validarTamanioTexto(txtPrecio.getText(), 0, 8, "PRECIO");
                ValidadorGeneral.validarTextoVacio(txtStock.getText(), "PRECIO");
                ValidadorGeneral.validarEnteroPositivo(txtPrecio.getText(), "PRECIO");
                producto.setPrecio(Integer.parseInt(txtPrecio.getText()));
                isPrecioValido = true;
            } catch (Exception Ex){
                JOptionPane.showMessageDialog(this, Ex.getMessage());
            }

            boolean isFechaSalidaValido = false;
            try {
                ValidadorGeneral.validarTamanioTexto(txtFechaSalida.getText(), 0, 10, "FECHA_SALIDA");
                ValidadorGeneral.validarTextoVacio(txtFechaSalida.getText(), "FECHA_SALIDA");
                producto.setFechaSalida(txtFechaSalida.getText());
                isFechaSalidaValido = true;
            } catch (Exception Ex){
               JOptionPane.showMessageDialog(this, Ex.getMessage());
            }

            boolean isDescripcionValido = false;
            try {
                ValidadorGeneral.validarTamanioTexto(txtDescripcion.getText(), 0, 80, "DESCRIPCION");
                ValidadorGeneral.validarTextoVacio(txtDescripcion.getText(), "DESCRIPCION");
                producto.setDescripcion(txtDescripcion.getText());
                isDescripcionValido = true;
            } catch (Exception Ex){
                JOptionPane.showMessageDialog(this, Ex.getMessage());
            }


            boolean isCantidadSobreValido = false;
            boolean isCantidadMazoValido = false;
            boolean isCantidadSobreEspecialValido = false;
            boolean isCartaPromoValido = false;
            boolean isRegaloExtraValido = false;


            if (producto instanceof CajaSobre) {
                try {
                    ValidadorGeneral.validarEnteroPositivo(txtCantidadSobre.getText(), "CANTIDAD_SOBRE");
                    ValidadorGeneral.validarTamanioTexto(txtCantidadSobre.getText(), 0, 4, "CANTIDAD_SOBRE");
                    ValidadorGeneral.validarTextoVacio(txtCantidadSobre.getText(), "CANTIDAD_SOBRE");
                    ((CajaSobre) producto).setCantidadPorCaja(Integer.parseInt(txtCantidadSobre.getText()));
                    isCantidadSobreValido = true;
                } catch (Exception Ex) {
                    JOptionPane.showMessageDialog(this, Ex.getMessage());
                }
            }


            else if (producto instanceof CajaMazo) {
                try {
                    ValidadorGeneral.validarTamanioTexto(txtCantidadMazos.getText(), 0, 4, "CANTIDAD_MAZO");
                    ValidadorGeneral.validarEnteroPositivo(txtCantidadMazos.getText(), "CANTIDAD_MAZO");
                    ValidadorGeneral.validarTextoVacio(txtCantidadMazos.getText(), "CANTIDAD_MAZO");
                    ((CajaMazo) producto).setCantidadPorCaja(Integer.parseInt(txtCantidadMazos.getText()));
                    isCantidadMazoValido = true;
                } catch (Exception Ex) {
                    JOptionPane.showMessageDialog(this, Ex.getMessage());
                }
            }


            else if (producto instanceof CajaEspecial) {
                try {
                    ValidadorGeneral.validarEnteroPositivo(txtCantidadSobresEspeciales.getText(), "CANTIDAD_SOBRE_ESPECIAL");
                    ValidadorGeneral.validarTamanioTexto(txtCantidadSobre.getText(), 0, 4, "CANTIDAD_SOBRE");
                    ValidadorGeneral.validarTextoVacio(txtCantidadSobre.getText(), "CANTIDAD_SOBRE");
                    ((CajaEspecial) producto).setCantidadSobres(Integer.parseInt(txtCantidadSobresEspeciales.getText()));
                    isCantidadSobreEspecialValido = true;
                } catch (Exception Ex) {
                    JOptionPane.showMessageDialog(this, Ex.getMessage());
                }

                try {
                    ValidadorGeneral.validarTamanioTexto(txtCartaPromocional.getText(), 0, 80, "CARTA_PROMO");
                    ValidadorGeneral.validarTextoVacio(txtCartaPromocional.getText(), "CARTA_PROMO");
                    ((CajaEspecial) producto).setCartasPromo(txtCartaPromocional.getText());
                    isCartaPromoValido = true;
                } catch (Exception Ex) {
                    JOptionPane.showMessageDialog(this, Ex.getMessage());
                }

                try {
                    ValidadorGeneral.validarTamanioTexto(txtRegaloEspecial.getText(), 0, 80, "REGALO_EXTRA");
                    ValidadorGeneral.validarTextoVacio(txtCartaPromocional.getText(), "CARTA_PROMO");
                    ((CajaEspecial) producto).setRegaloExtra(txtRegaloEspecial.getText());
                    isRegaloExtraValido = true;
                } catch (Exception Ex) {
                    JOptionPane.showMessageDialog(this, Ex.getMessage());
                }
            }


            boolean isTipoProductoValido = false;
            if (producto instanceof CajaSobre) {
                isTipoProductoValido = isCantidadSobreValido;
            } else if (producto instanceof CajaMazo) {
                isTipoProductoValido = isCantidadMazoValido;
            } else if (producto instanceof CajaEspecial) {
                isTipoProductoValido = isCantidadSobreEspecialValido && isCartaPromoValido && isRegaloExtraValido;
            }


            if (isSKUValido && isNombreValido && isEdicionValido && isLineaValido && isTipoValido
               && isStockValido && isPrecioValido && isFechaSalidaValido 
               && isDescripcionValido && isTipoProductoValido) {

                ProductoDAO dao = new ProductoDAO();
                boolean resultado = dao.insertar(producto);

                System.out.println("actualizar -> " + resultado);

            if (resultado) {
                    JOptionPane.showMessageDialog(this, "El Producto se agregó correctamente");
                    limpiarCampos();

                    this.producto = null;
                } else {
                    JOptionPane.showMessageDialog(this, "Error al agregar el producto");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Por favor corrija los errores en los campos antes de guardar");
            }
    }
    
    else if ("Editar Productos".equals(cmbOpcion.getSelectedItem())) {
        
        if (this.producto == null) {
        JOptionPane.showMessageDialog(this, "Primero debe buscar el producto con la Lupa (ingrese SKU) para poder editarlo.");
        return;
        }
        
        
        boolean isNombreValido = false;
        try {
            ValidadorGeneral.validarTamanioTexto(txtNombre.getText(), 0, 50, "NOMBRE");
            producto.setNombre(txtNombre.getText());
            isNombreValido = true;
        } catch (Exception Ex){
            JOptionPane.showMessageDialog(this, "Error en nombre: " + Ex.getMessage());
        }
        
        boolean isEdicionValido = false;
        try {
            ValidadorGeneral.validarTamanioTexto(txtEdicion.getText(), 0, 50, "EDICION");
            producto.setEdicion(txtEdicion.getText());
            isEdicionValido = true;
        } catch (Exception Ex){
            JOptionPane.showMessageDialog(this, "Error en edición: " + Ex.getMessage());
        }
        

        boolean isLineaValido = false;
        try {
            ValidadorGeneral.validarTamanioTexto(txtLinea.getText(), 0, 50, "LINEA");
            producto.setLinea(txtLinea.getText());
            isLineaValido = true;
        } catch (Exception Ex){
            JOptionPane.showMessageDialog(this, "Error en línea: " + Ex.getMessage());
        }
        
        boolean isStockValido = false;
        try {
            ValidadorGeneral.validarTamanioTexto(txtStock.getText(), 0, 4, "STOCK");
            producto.setStock(Integer.parseInt(txtStock.getText()));
            isStockValido = true;
        } catch (Exception Ex){
            JOptionPane.showMessageDialog(this, "Error en stock: " + Ex.getMessage());
        }
        
        boolean isPrecioValido = false;
        try {
            ValidadorGeneral.validarTamanioTexto(txtPrecio.getText(), 0, 8, "PRECIO");
            ValidadorGeneral.validarEnteroPositivo(txtPrecio.getText(), "PRECIO");
            producto.setPrecio(Integer.parseInt(txtPrecio.getText()));
            isPrecioValido = true;
        } catch (Exception Ex){
            JOptionPane.showMessageDialog(this, "Error en precio: " + Ex.getMessage());
        }
        
        boolean isFechaSalidaValido = false;
        try {
            ValidadorGeneral.validarTamanioTexto(txtFechaSalida.getText(), 0, 10, "FECHA_SALIDA");
            producto.setFechaSalida(txtFechaSalida.getText());
            isFechaSalidaValido = true;
        } catch (Exception Ex){
            JOptionPane.showMessageDialog(this, "Error en fecha salida: " + Ex.getMessage());
        }
        
        boolean isDescripcionValido = false;
        try {
            ValidadorGeneral.validarTamanioTexto(txtDescripcion.getText(), 0, 80, "DESCRIPCION");
            producto.setDescripcion(txtDescripcion.getText());
            isDescripcionValido = true;
        } catch (Exception Ex){
            JOptionPane.showMessageDialog(this, "Error en descripción: " + Ex.getMessage());
        }
        
       
        boolean isCantidadSobreValido = false;
        boolean isCantidadMazoValido = false;
        boolean isCantidadSobreEspecialValido = false;
        boolean isCartaPromoValido = false;
        boolean isRegaloExtraValido = false;
        
        
        if (producto instanceof CajaSobre) {
            try {
                ValidadorGeneral.validarNumeroEntero(txtCantidadSobre.getText(), "CANTIDAD_SOBRE");
                ValidadorGeneral.validarTamanioTexto(txtCantidadSobre.getText(), 0, 4, "CANTIDAD_SOBRE");
                ((CajaSobre) producto).setCantidadPorCaja(Integer.parseInt(txtCantidadSobre.getText()));
                isCantidadSobreValido = true;
            } catch (Exception Ex) {
                JOptionPane.showMessageDialog(this, "Error en cantidad sobre: " + Ex.getMessage());
            }
        }
        
      
        else if (producto instanceof CajaMazo) {
            try {
                ValidadorGeneral.validarTamanioTexto(txtCantidadMazos.getText(), 0, 4, "CANTIDAD_MAZO");
                ((CajaMazo) producto).setCantidadPorCaja(Integer.parseInt(txtCantidadMazos.getText()));
                isCantidadMazoValido = true;
            } catch (Exception Ex) {
                JOptionPane.showMessageDialog(this, "Error en cantidad mazo: " + Ex.getMessage());
            }
        }
        
        
        else if (producto instanceof CajaEspecial) {
            try {
                ValidadorGeneral.validarNumeroEntero(txtCantidadSobresEspeciales.getText(), "CANTIDAD_SOBRE_ESPECIAL");
                ValidadorGeneral.validarTamanioTexto(txtCantidadSobre.getText(), 0, 4, "CANTIDAD_SOBRE");
                ((CajaEspecial) producto).setCantidadSobres(Integer.parseInt(txtCantidadSobresEspeciales.getText()));
                isCantidadSobreEspecialValido = true;
            } catch (Exception Ex) {
                JOptionPane.showMessageDialog(this, "Error en cantidad sobres especiales: " + Ex.getMessage());
            }
            
            try {
                ValidadorGeneral.validarTamanioTexto(txtCartaPromocional.getText(), 0, 80, "CARTA_PROMO");
                ((CajaEspecial) producto).setCartasPromo(txtCartaPromocional.getText());
                isCartaPromoValido = true;
            } catch (Exception Ex) {
                JOptionPane.showMessageDialog(this, "Error en carta promocional: " + Ex.getMessage());
            }
            
            try {
                ValidadorGeneral.validarTamanioTexto(txtRegaloEspecial.getText(), 0, 80, "REGALO_EXTRA");
                ((CajaEspecial) producto).setRegaloExtra(txtRegaloEspecial.getText());
                isRegaloExtraValido = true;
            } catch (Exception Ex) {
                JOptionPane.showMessageDialog(this, "Error en regalo extra: " + Ex.getMessage());
            }
        }
        
        
       
        boolean isTipoProductoValido = false;
        if (producto instanceof CajaSobre) {
            isTipoProductoValido = isCantidadSobreValido;
        } else if (producto instanceof CajaMazo) {
            isTipoProductoValido = isCantidadMazoValido;
        } else if (producto instanceof CajaEspecial) {
            isTipoProductoValido = isCantidadSobreEspecialValido && isCartaPromoValido && isRegaloExtraValido;
        }
        
    
        if (isNombreValido && isEdicionValido && isLineaValido
           && isStockValido && isPrecioValido && isFechaSalidaValido 
           && isDescripcionValido && isTipoProductoValido) {
            
            ProductoDAO dao = new ProductoDAO();
            boolean resultado = dao.actualizarProducto(producto);

            System.out.println("actualizar -> " + resultado);

            if (resultado) {
                JOptionPane.showMessageDialog(this, "El Producto se modificó correctamente");
                limpiarCampos();
   
                this.producto = null;
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar en la Base de Datos");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor corrija los errores en los campos antes de guardar");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed
 }
    private void txtSKUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSKUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSKUActionPerformed

    private void txtCartaPromocionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCartaPromocionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCartaPromocionalActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
          if ("Caja Mazos".equals(cmbTipo.getSelectedItem())){
              accionCajaMazo();
          }
          
          if ("Caja Sobres".equals(cmbTipo.getSelectedItem())){
              accionCajaSobre();
          }
          
          if ("Caja Especial".equals(cmbTipo.getSelectedItem())){
              accionCajaEspecial();
          }
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        FormularioListarProducto formListarProducto = new FormularioListarProducto();
        formListarProducto.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        String sku = txtSKU.getText();
        ProductoDAO dao = new ProductoDAO();
        boolean resultado = dao.eliminarProducto(sku); 
        System.out.println("borrar -> " + resultado);   
        
        if (sku.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Debe llenar campo"); 
        }else{
            if(resultado){
            
            JOptionPane.showMessageDialog(rootPane, "Producto eliminado");            
            limpiarCampos();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Producto no se elimino");                        
        }
        
        } 
        
               
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNombreActionPerformed

    private void cmbOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOpcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOpcionActionPerformed

    private void btnLupaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLupaActionPerformed

    String skuBuscado = txtSKU.getText().trim();

    if (skuBuscado.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Primero debe ingresar un SKU para buscar el producto",
            "Error",
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    ProductoDAO dao = new ProductoDAO();
    Producto p = dao.buscarPorSku(skuBuscado);

    if (p != null) {
        this.producto = p;
    } else {
        JOptionPane.showMessageDialog(this, "Producto no encontrado");
        this.producto = null;
        return;
    }

    txtNombre.setText(p.getNombre());
    txtEdicion.setText(p.getEdicion());
    txtLinea.setText(p.getLinea());
    txtStock.setText("" + p.getStock());
    txtPrecio.setText("" + p.getPrecio());
    txtFechaSalida.setText(p.getFechaSalida());
    txtDescripcion.setText(p.getDescripcion());

    if (p instanceof CajaMazo){
        txtCantidadMazos.setText("" + ((CajaMazo) p).getCantidadPorCaja());
    }else if (p instanceof CajaSobre){
        txtCantidadSobre.setText("" + ((CajaSobre) p).getCantidadPorCaja());
    }else if (p instanceof CajaEspecial){
        txtCantidadSobresEspeciales.setText("" + ((CajaEspecial) p).getCantidadSobres());
        txtCartaPromocional.setText(((CajaEspecial) p).getCartasPromo());
        txtRegaloEspecial.setText(((CajaEspecial) p).getRegaloExtra());




    if (this.producto == null) {
        JOptionPane.showMessageDialog(this, 
            "No se encontró ningún producto con el SKU: " + skuBuscado + "\n\nPor favor, verifique el SKU e intente nuevamente.",
            "Producto no encontrado",
            JOptionPane.WARNING_MESSAGE);
        return;
    }



        
    producto.setSku(txtSKU.getText());
   
    }
            

    }//GEN-LAST:event_btnLupaActionPerformed
    
      private void accionCajaMazo() {
          //enable txt
        txtSKU.setEnabled(true);
        txtNombre.setEnabled(true);
        txtEdicion.setEnabled(true);
        txtLinea.setEnabled(true);
        txtStock.setEnabled(true);
        txtPrecio.setEnabled(true);
        txtFechaSalida.setEnabled(true);
        txtDescripcion.setEnabled(true);
        txtCantidadSobre.setEnabled(false);
        txtCantidadMazos.setEnabled(true);
        txtCantidadSobresEspeciales.setEnabled(false);
        txtCartaPromocional.setEnabled(false);
        txtRegaloEspecial.setEnabled(false);
        //visible txt
        txtSKU.setVisible(true);
        txtNombre.setVisible(true);
        txtEdicion.setVisible(true);
        txtLinea.setVisible(true);
        txtStock.setVisible(true);
        txtPrecio.setVisible(true);
        txtFechaSalida.setVisible(true);
        txtDescripcion.setVisible(true);
        txtCantidadSobre.setVisible(true);
        txtCantidadMazos.setVisible(true);
        txtCantidadSobresEspeciales.setVisible(true);
        txtCartaPromocional.setVisible(true);
        txtRegaloEspecial.setVisible(true);
        lblCantidadSobre.setVisible(true);
        lblCantidadMazo.setVisible(true);
        lblCantidadSobreEspecial.setVisible(true);
        lblCartaPromo.setVisible(true);
        lblRegaloExtra.setVisible(true);
        this.pack(); 
        this.setLocationRelativeTo(null);
        
    }
    
    private void accionCajaSobre() {
        //enable txt
        txtSKU.setEnabled(true);
        txtNombre.setEnabled(true);
        txtEdicion.setEnabled(true);
        txtLinea.setEnabled(true);
        txtStock.setEnabled(true);
        txtPrecio.setEnabled(true);
        txtFechaSalida.setEnabled(true);
        txtDescripcion.setEnabled(true);
        txtCantidadSobre.setEnabled(true);
        txtCantidadMazos.setEnabled(false);
        txtCantidadSobresEspeciales.setEnabled(false);
        txtCartaPromocional.setEnabled(false);
        txtRegaloEspecial.setEnabled(false);
        //visible txt
        txtSKU.setVisible(true);
        txtNombre.setVisible(true);
        txtEdicion.setVisible(true);
        txtLinea.setVisible(true);
        txtStock.setVisible(true);
        txtPrecio.setVisible(true);
        txtFechaSalida.setVisible(true);
        txtDescripcion.setVisible(true);
        txtCantidadSobre.setVisible(true);
        txtCantidadMazos.setVisible(true);
        txtCantidadSobresEspeciales.setVisible(true);
        txtCartaPromocional.setVisible(true);
        txtRegaloEspecial.setVisible(true);
        lblCantidadSobre.setVisible(true);
        lblCantidadMazo.setVisible(true);
        lblCantidadSobreEspecial.setVisible(true);
        lblCartaPromo.setVisible(true);
        lblRegaloExtra.setVisible(true);
        this.pack(); 
        this.setLocationRelativeTo(null);
        
    }
    
    private void accionCajaEspecial() {
        //enable txt
        txtSKU.setEnabled(true);
        txtNombre.setEnabled(true);
        txtEdicion.setEnabled(true);
        txtLinea.setEnabled(true);
        txtStock.setEnabled(true);
        txtPrecio.setEnabled(true);
        txtFechaSalida.setEnabled(true);
        txtDescripcion.setEnabled(true);
        txtCantidadSobre.setEnabled(false);
        txtCantidadMazos.setEnabled(false);
        txtCantidadSobresEspeciales.setEnabled(true);
        txtCartaPromocional.setEnabled(true);
        txtRegaloEspecial.setEnabled(true);
        //visible txt
        txtSKU.setVisible(true);
        txtNombre.setVisible(true);
        txtEdicion.setVisible(true);
        txtLinea.setVisible(true);
        txtStock.setVisible(true);
        txtPrecio.setVisible(true);
        txtFechaSalida.setVisible(true);
        txtDescripcion.setVisible(true);
        txtCantidadSobre.setVisible(true);
        txtCantidadMazos.setVisible(true);
        txtCantidadSobresEspeciales.setVisible(true);
        txtCartaPromocional.setVisible(true);
        txtRegaloEspecial.setVisible(true);
        lblCantidadSobre.setVisible(true);
        lblCantidadMazo.setVisible(true);
        lblCantidadSobreEspecial.setVisible(true);
        lblCartaPromo.setVisible(true);
        lblRegaloExtra.setVisible(true);
        this.pack(); 
        this.setLocationRelativeTo(null);

    }
    
    private void limpiarCampos() {
        txtSKU.setText("");
        txtNombre.setText("");
        txtEdicion.setText("");
        txtLinea.setText("");
        txtStock.setText("");
        txtPrecio.setText("");
        txtFechaSalida.setText("");
        txtDescripcion.setText("");
        txtCantidadSobre.setText("");
        txtCantidadMazos.setText("");
        txtCantidadSobresEspeciales.setText("");
        txtCartaPromocional.setText("");
        txtRegaloEspecial.setText("");
        
        txtSKU.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        java.awt.EventQueue.invokeLater(() -> new DistribuidoraVIew().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLupa;
    private javax.swing.JComboBox<String> cmbOpcion;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCantidadMazo;
    private javax.swing.JLabel lblCantidadSobre;
    private javax.swing.JLabel lblCantidadSobreEspecial;
    private javax.swing.JLabel lblCartaPromo;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEdicion;
    private javax.swing.JLabel lblFechaSalida;
    private javax.swing.JLabel lblLinea;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblRegaloExtra;
    private javax.swing.JLabel lblSKU;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTextField txtCantidadMazos;
    private javax.swing.JTextField txtCantidadSobre;
    private javax.swing.JTextField txtCantidadSobresEspeciales;
    private javax.swing.JTextField txtCartaPromocional;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtEdicion;
    private javax.swing.JTextField txtFechaSalida;
    private javax.swing.JTextField txtLinea;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtRegaloEspecial;
    private javax.swing.JTextField txtSKU;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
