package view;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import controller.*;
import model.*;

/**
 *
 * @author Vitoco
 */
public class FormularioListarProducto extends javax.swing.JFrame {
    private static FormularioListarProducto instanciaActual = null;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormularioListarProducto.class.getName());

    /**
     * Creates new form FormularioListarProducto
     */
    public FormularioListarProducto() {
        if (instanciaActual != null) {
            instanciaActual.dispose(); 
        }
        instanciaActual = this;


        initComponents(); 
        

        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        this.setLocationRelativeTo(null);
        

        ProductoDAO dao = new ProductoDAO();
        jtListar.getColumnModel().getColumn(0).setPreferredWidth(80); 
        jtListar.getColumnModel().getColumn(1).setPreferredWidth(240); 
        jtListar.getColumnModel().getColumn(2).setPreferredWidth(50);
        jtListar.getColumnModel().getColumn(3).setPreferredWidth(70);
        jtListar.getColumnModel().getColumn(4).setPreferredWidth(60);
        jtListar.getColumnModel().getColumn(5).setPreferredWidth(70); 
        jtListar.getColumnModel().getColumn(6).setPreferredWidth(35); 
        jtListar.getColumnModel().getColumn(7).setPreferredWidth(70); 
        jtListar.getColumnModel().getColumn(8).setPreferredWidth(390);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cmbListar = new javax.swing.JComboBox<>();
        btnListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListar = new javax.swing.JTable();
        txtBuscarSkuListar = new javax.swing.JTextField();
        btnBuscarListar = new javax.swing.JButton();
        cmbBuscarPor = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbListar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todo", "Cajas Sobres", "Cajas Mazos", "Cajas Especial" }));
        cmbListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbListarActionPerformed(evt);
            }
        });

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        jtListar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sku", "Nombre", "Edicion", "Linea", "Fecha", "Precio", "Stock", "Tipo", "InfoEspecifica"
            }
        ));
        jScrollPane1.setViewportView(jtListar);

        txtBuscarSkuListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarSkuListarActionPerformed(evt);
            }
        });

        btnBuscarListar.setText("Buscar");
        btnBuscarListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarListarActionPerformed(evt);
            }
        });

        cmbBuscarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buscar por SKU", "Buscar por Nombre" }));
        cmbBuscarPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBuscarPorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cmbListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btnListar)
                        .addGap(41, 41, 41)
                        .addComponent(cmbBuscarPor, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscarSkuListar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarListar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar)
                    .addComponent(txtBuscarSkuListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarListar)
                    .addComponent(cmbBuscarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbListarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbListarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        ProductoDAO dao = new ProductoDAO();
        
        DefaultTableModel modelo = (DefaultTableModel) jtListar.getModel();

       
        modelo.setRowCount(0);
        String seleccionUsuario = cmbListar.getSelectedItem().toString();
        String filtroParaBD = null;
        switch (seleccionUsuario) {
            case "Cajas Sobres":
                filtroParaBD = "Caja Sobres";
                break;
            case "Cajas Mazos":
                filtroParaBD = "Caja Mazos";
                break;
            case "Cajas Especial":
                filtroParaBD = "Caja Especial";
                break;
            case "Todo":
                filtroParaBD = null;
                break;
        }
        List<Producto> listaProductos = dao.listar(filtroParaBD);
        
        for (Producto p : listaProductos) {

        String infoEspecifica = "";
        
        if (p instanceof CajaSobre) {
            
            CajaSobre cs = (CajaSobre) p;
            infoEspecifica = "Sobres/Caja: " + cs.getCantidadPorCaja();
            
        } else if (p instanceof CajaMazo) {
            CajaMazo cm = (CajaMazo) p;
            infoEspecifica = "Mazos/Caja: " + cm.getCantidadPorCaja(); 
            
        } else if (p instanceof CajaEspecial) {
            CajaEspecial ce = (CajaEspecial) p;
            infoEspecifica = String.format("Sobres: %d | Promo: %s | Regalo: %s", 
                                           ce.getCantidadSobres(), 
                                           ce.getCartasPromo(), 
                                           ce.getRegaloExtra());
        }

        Object[] fila = new Object[] {
            p.getSku(),
            p.getNombre(),
            p.getEdicion(),
            p.getLinea(), 
            p.getFechaSalida(),
            p.getPrecio(),
            p.getStock(),
            p.getTipo(),    
            infoEspecifica  
        };
        
        modelo.addRow(fila);
    }

    }//GEN-LAST:event_btnListarActionPerformed

    private void txtBuscarSkuListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarSkuListarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarSkuListarActionPerformed

    private void btnBuscarListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarListarActionPerformed
        // TODO add your handling code here:
    String buscarUsuario = cmbBuscarPor.getSelectedItem().toString();    
    if (buscarUsuario.equals("Buscar por SKU")){
        String skuBuscado = txtBuscarSkuListar.getText().trim();

    if (skuBuscado.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor escribe el SKU que deseas buscar.");
        return;
    }

    ProductoDAO dao = new ProductoDAO();
    
    Producto p = dao.buscarPorSku(skuBuscado);

    if (p == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "No se encontró ningún producto con el SKU: " + skuBuscado);
        ((DefaultTableModel) jtListar.getModel()).setRowCount(0);
    } else {
        DefaultTableModel modelo = (DefaultTableModel) jtListar.getModel();
        modelo.setRowCount(0);

        String infoEspecifica = "";
        
        if (p instanceof CajaSobre) {
            CajaSobre cs = (CajaSobre) p;
            infoEspecifica = "Sobres/Caja: " + cs.getCantidadPorCaja();
            
        } else if (p instanceof CajaMazo) {
            CajaMazo cm = (CajaMazo) p;
            infoEspecifica = "Mazos/Caja: " + cm.getCantidadPorCaja(); 
            
        } else if (p instanceof CajaEspecial) {
            CajaEspecial ce = (CajaEspecial) p;
            infoEspecifica = String.format("Sobres: %d | Promo: %s | Regalo: %s", 
                                           ce.getCantidadSobres(), 
                                           ce.getCartasPromo(), 
                                           ce.getRegaloExtra());
        }

        Object[] fila = new Object[] {
            p.getSku(),
            p.getNombre(),
            p.getEdicion(),
            p.getLinea(), 
            p.getFechaSalida(),
            p.getPrecio(),
            p.getStock(),
            p.getTipo(),    
            infoEspecifica 
        };
        
        modelo.addRow(fila);
    }
    } else if (buscarUsuario.equals("Buscar por Nombre")) {
    String nombreBuscado = txtBuscarSkuListar.getText().trim();

    if (nombreBuscado.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor escribe el Nombre que deseas buscar.");
        return;
    }

    ProductoDAO dao = new ProductoDAO();
    
    List<Producto> listaResultados = dao.buscarPorNombre(nombreBuscado);

    if (listaResultados.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "No se encontró ningún producto con el Nombre: " + nombreBuscado);
        ((DefaultTableModel) jtListar.getModel()).setRowCount(0);
    } else {
        DefaultTableModel modelo = (DefaultTableModel) jtListar.getModel();
        modelo.setRowCount(0);
        
        for (Producto prodIterado : listaResultados) { 
            
            String infoEspecifica = "";
            
            // Usamos 'prodIterado' en los instanceof
            if (prodIterado instanceof CajaSobre) {
                infoEspecifica = "Sobres/Caja: " + ((CajaSobre) prodIterado).getCantidadPorCaja();
                
            } else if (prodIterado instanceof CajaMazo) {
                infoEspecifica = "Mazos/Caja: " + ((CajaMazo) prodIterado).getCantidadPorCaja(); 
                
            } else if (prodIterado instanceof CajaEspecial) {
                CajaEspecial ce = (CajaEspecial) prodIterado;
                infoEspecifica = String.format("Sobres: %d | Promo: %s | Regalo: %s", 
                                               ce.getCantidadSobres(), 
                                               ce.getCartasPromo(), 
                                               ce.getRegaloExtra());
            }

            Object[] fila = new Object[] {
                prodIterado.getSku(),     
                prodIterado.getNombre(),   
                prodIterado.getEdicion(),
                prodIterado.getLinea(), 
                prodIterado.getFechaSalida(),
                prodIterado.getPrecio(),
                prodIterado.getStock(),
                prodIterado.getTipo(),     
                infoEspecifica 
            };
            
            modelo.addRow(fila);
        }
    }

    }
    }//GEN-LAST:event_btnBuscarListarActionPerformed

    private void cmbBuscarPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBuscarPorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBuscarPorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormularioListarProducto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarListar;
    private javax.swing.JButton btnListar;
    private javax.swing.JComboBox<String> cmbBuscarPor;
    private javax.swing.JComboBox<String> cmbListar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtListar;
    private javax.swing.JTextField txtBuscarSkuListar;
    // End of variables declaration//GEN-END:variables
}
